---
charts:
  - name: qubership-cassandra-supplementary
    chart_file: charts/helm/cassandra-services/Chart.yaml
    values_file: charts/helm/cassandra-services/values.yaml
    image:
      - ghcr.io/netcracker/qubership-cassandra-supplementary:${release}
      - ghcr.io/netcracker/qubership-cassandra-supplementary-transfer:${release}
      - ghcr.io/netcracker/qubership-cassandra-dbaas-adapter:${release}
      - ghcr.io/netcracker/qubership-cassandra-backup-daemon:${release}
      - ghcr.io/netcracker/qubership-cassandra-tests:${release}
