# permissions for end users to edit cassandrasupplservice.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cassandrasupplservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cassandra-services
    app.kubernetes.io/part-of: cassandra-services
    app.kubernetes.io/managed-by: kustomize
  name: cassandrasupplservice-editor-role
rules:
- apiGroups:
  - netcracker.com
  resources:
  - cassandrasupplservice
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netcracker.com
  resources:
  - cassandrasupplservice/status
  verbs:
  - get
