{{- if .Values.dbaas.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nc-dbaas-physical-databases-labels
  labels:
    app: nc-dbaas-cassandra-adapter
    name: nc-dbaas-cassandra-adapter
      {{ include "kubernetes.labels" . | nindent  4}}
data:
  dbaas.physical_databases.registration.labels.json: {{ .Values.dbaas.labels | toJson | quote }}
{{- end }}