kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cassandra-services
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
roleRef:
  kind: Role
  name: cassandra-services
  apiGroup: rbac.authorization.k8s.io