{{- if and (.Values.backupDaemon.install) (and (not .Values.tls.generateCerts.enabled) .Values.tls.enabled) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.backupDaemon.tls.backupDaemonCASecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cassandra.defaultLabels" . | nindent 4 }}
data:
  {{ .Values.tls.rootCAFileName }}: {{ .Values.tls.certificates.ca_crt }}
  {{ .Values.tls.privateKeyFileName }}: {{ .Values.backupDaemon.tls.certificates.tls_key }}
  {{ .Values.tls.signedCRTFileName }}: {{ .Values.backupDaemon.tls.certificates.tls_crt }}
type: Opaque
{{ end }}