{{- if and (eq (include "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.dbaas.install "envVar" .Values.DBAAS_ENABLED "default" true )) "true")   (and .Values.tls.enabled .Values.tls.generateCerts.enabled) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dbaas-tls-certificate
  labels:
    {{- include "cassandra.defaultLabels" . | nindent 4 }}
spec:
  secretName: {{ .Values.dbaas.tls.dbaasAdapterCASecretName }}
  duration: {{ default 365 .Values.tls.generateCerts.duration | mul 24 }}h
  commonName: dbaas-certs-cn
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
{{ ( include "dbaasAdapter.certDnsNames" . | indent 4 ) }}
  ipAddresses:
{{ ( include "common.certIpAddresses" . | indent 4) }}
  issuerRef:
    group: cert-manager.io
  {{- if .Values.tls.generateCerts.clusterIssuerName }}
    name: {{ .Values.tls.generateCerts.clusterIssuerName }}
    kind: ClusterIssuer
  {{- else }}
    name: cassandra-tls-issuer
    kind: Issuer
  {{- end }}
{{- end }}