{{- if and (eq (include "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.dbaas.install "envVar" .Values.DBAAS_ENABLED "default" true )) "true") (and (not .Values.tls.generateCerts.enabled ) (.Values.tls.enabled)) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.dbaas.tls.dbaasAdapterCASecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cassandra.defaultLabels" . | nindent 4 }}
data:
  {{ .Values.tls.rootCAFileName }}: {{ .Values.tls.certificates.ca_crt }}
  {{ .Values.tls.privateKeyFileName }}: {{ .Values.dbaas.tls.certificates.tls_key }}
  {{ .Values.tls.signedCRTFileName }}: {{ .Values.dbaas.tls.certificates.tls_crt }}
type: Opaque
{{ end }}