{{- if .Values.awsKeyspaces.install }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-keyspaces-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cassandra.defaultLabels" . | nindent 4 }}
stringData:
  accessKey: {{ .Values.awsKeyspaces.accessKey | quote }}
  secretKey: {{ .Values.awsKeyspaces.secretKey | quote }}
  region: {{ .Values.awsKeyspaces.region | quote }}
type: Opaque
{{ end }}