{{- if eq (include "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.dbaas.install "envVar" .Values.DBAAS_ENABLED "default" true )) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: dbaas-streaming-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cassandra.defaultLabels" . | nindent 4 }}
stringData:
  name: {{ .Values.dbaas.dbaasStreamingRoleName | quote }}
  roles: {{ .Values.dbaas.dbaasStreamingRoles | quote }}
type: Opaque
{{ end }}