{{- if .Values.vaultRegistration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vaultRegistration.tokenSecretName }}
data:
  {{- if .Values.VAULT_TOKEN }}
  token: {{ .Values.VAULT_TOKEN | b64enc }}
  {{- else }}
  token: {{ default "#" .Values.vaultRegistration.token | b64enc }}
  {{- end }}
type: Opaque
{{- end }}
